/***************************************************************************************
                  Silicon Laboratories Broadcast Digital Radio SDK

   EVALUATION AND USE OF THIS SOFTWARE IS SUBJECT TO THE TERMS AND CONDITIONS OF
     THE SOFTWARE LICENSE AGREEMENT IN THE DOCUMENTATION FILE CORRESPONDING
     TO THIS SOURCE FILE.
   IF YOU DO NOT AGREE TO THE LIMITED LICENSE AND CONDITIONS OF SUCH AGREEMENT,
     PLEASE RETURN ALL SOURCE FILES TO SILICON LABORATORIES.

   SDK->MMI callback definitions
   FILE: SDK_Callbacks.h
   Supported IC : Si468x
   Date: June 20 2014
  (C) Copyright 2014, Silicon Laboratories, Inc. All rights reserved.
****************************************************************************************/

#ifndef __SI46XX_SDK_CALLBACKS__
#define __SI46XX_SDK_CALLBACKS__

#include "common_types.h"
#include "platform_options.h"
#include "feature_types.h"
#include "Firmware_API_Manager.h"

typedef enum _SDK_CALLBACKS_UPDATED_DATA_TYPE
{
    //RDS
    UPDATED_RDS_PI,
    UPDATED_RDS_PTY,
    UPDATED_RDS_RT,
    UPDATED_RDS_PST,
    UPDATED_RDS_TIME,
    UPDATED_RDS_ALT_FREQ,
    //SIS
    UPDATED_SIS_SLOGAN,
    UPDATED_SIS_UNIVERSAL_SHORT_NAME,
    UPDATED_SIS_STATION_MESSAGE,
    UPDATED_SIS_STATION_NAME_LONG,
    UPDATED_SIS_STATION_NAME_SHORT,
    UPDATED_SIS_STATION_ID,
    UPDATED_SIS_LOC_LAT,
    UPDATED_SIS_LOC_LON,
    //PSD
    UPDATED_PSD_TITLE,
    UPDATED_PSD_ARTIST,
    UPDATED_PSD_ALBUM,
    UPDATED_PSD_GENRE,
    //HD Alerts
    UPDATED_HD_ALERT,
    //DLS
    UPDATED_DLS_STRING,
    CLEAR_DLS_COMMAND,
    //SERVICE LIST
    //SERVICE LIST-FMHD
    UPDATED_SERVICE_LIST_FAST,
    UPDATED_SERVICE_LIST_AUDIO,
    UPDATED_SERVICE_LIST_DATA,
    //SERVICE LIST-DAB
    DAB_SERVICE_LIST_REQUIRED_UPDATE,
    UPDATED_SERVICE_LIST_DAB,
    UPDATED_SERVICE_LINKING_DAB,
    //DAB NOTIFICATIONS
    SERVICE_LIST_BUFFER_FULL_ERROR,
    DAB_TUNE_SCAN_PROCESS_UPDATE,
    DAB_TUNE_REQUIRED_UPDATE,
    DAB_TUNE_SCAN_PROCESS_COMPLETE,
    //DAB-EVENTS
    EVENT_ENSEMBLE_RECONFIGURATION,
    EVENT_ENSEMBLE_RECONFIGURATION_WARNING,
    EVENT_CURRENT_SERVICE_NO_LONGER_AVAILABLE,
    EVENT_FINDING_ALTERNATE_SERVICE,
    //Special
    EVENT_READY_FOR_FIRMWARE_UPDATE,
    DAB_FRONT_END_CAL_PROCESS_UPDATE,
    //FM/FMHD SEEK NOTIFICATIONS
    FM_SEEK_PROCESS_UPDATE,
    FM_SEEK_PROCESS_COMPLETE,
	
	//am seek notifications
	AM_SEEK_PROCESS_UPDATE,
	AM_SEEK_PROCESS_COMPLETE,
    //Undefined
    UPDATED_UNKNOWN
}SDK_CALLBACKS_UPDATED_DATA_TYPE;

extern void CALLBACK_Updated_Data(SDK_CALLBACKS_UPDATED_DATA_TYPE updatedType);

#define    UPDATED_RDS_PI_ITEM			0x01
#define    UPDATED_RDS_PTY_ITEM			0x02
#define    UPDATED_RDS_RT_ITEM			0x04
#define    UPDATED_RDS_PST_ITEM			0x08	
#define    UPDATED_RDS_TIME_ITEM		0x10
#define    UPDATED_RDS_ALT_FREQ_ITEM	0x20


#define    UPDATED_SIS_SLOGAN_ITEM					0x01
#define    UPDATED_SIS_UNIVERSAL_SHORT_NAME_ITEM	0x02
#define    UPDATED_SIS_STATION_MESSAGE_ITEM			0x04
#define    UPDATED_SIS_STATION_NAME_LONG_ITEM		0x08
#define    UPDATED_SIS_STATION_NAME_SHORT_ITEM		0x10
#define    UPDATED_SIS_STATION_ID_ITEM				0x20
#define    UPDATED_SIS_LOC_LAT_ITEM					0x40
#define    UPDATED_SIS_LOC_LON_ITEM					0x80


#define    UPDATED_PSD_TITLE_ITEM		0x01
#define    UPDATED_PSD_ARTIST_ITEM		0x02
#define    UPDATED_PSD_ALBUM_ITEM		0x04
#define    UPDATED_PSD_GENRE_ITEM		0x08

#define    UPDATED_ALERT_ITEM           0x01

#define    UPDATED_DLS_STRING_ITEM			0x01

#endif

